#!/usr/bin/env python3
"""Pre-demo setup: create onboarded accounts with valid registration tokens.

Connects to the staging database via Cloud SQL Proxy (must be running)
and inserts accounts + verified email records so the demo scripts can
register agents without going through the email flow.

Usage:
    # Start Cloud SQL Proxy first:
    cloud-sql-proxy agent-registry-488317:us-west1:agent-registry-staging &

    # Then run:
    python3 demo_setup.py

Outputs a .env.demo file with registration tokens for Alice and Bob.
"""

import os
import secrets
import sys
import uuid
from datetime import UTC, datetime, timedelta

from demo_db import get_connection

ALICE_EMAIL = "alice-demo@arcoa.ai"
BOB_EMAIL = "bob-demo@arcoa.ai"

# Registration tokens valid for 1 hour
TOKEN_LIFETIME = timedelta(hours=1)

# ─── Colors ───
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
DIM = "\033[2m"
BOLD = "\033[1m"
RESET = "\033[0m"


def main() -> None:
    print(f"{BOLD}Demo Setup — Creating onboarded accounts{RESET}")
    print(f"{DIM}Connecting to database...{RESET}")

    conn = get_connection()
    conn.autocommit = False
    cur = conn.cursor()

    now = datetime.now(UTC)
    token_expires = now + TOKEN_LIFETIME
    tokens = {}

    for email, name in [(ALICE_EMAIL, "Alice"), (BOB_EMAIL, "Bob")]:
        print(f"\n{YELLOW}Setting up {name} ({email})...{RESET}")

        # Clean up any existing demo data for this email
        # Delete agent if exists (cascades through jobs, etc.)
        cur.execute("""
            SELECT a.agent_id FROM accounts acc
            JOIN agents a ON a.agent_id = acc.agent_id
            WHERE acc.email = %s
        """, (email,))
        row = cur.fetchone()
        if row:
            agent_id = row[0]
            print(f"  {DIM}Cleaning up existing agent {str(agent_id)[:8]}...{RESET}")
            # Null out the account's agent_id first to avoid FK issues
            cur.execute("UPDATE accounts SET agent_id = NULL WHERE email = %s", (email,))
            cur.execute("DELETE FROM agents WHERE agent_id = %s", (agent_id,))

        # Clean up old verifications
        cur.execute("DELETE FROM email_verifications WHERE email = %s", (email,))

        # Upsert account
        account_id = uuid.uuid4()
        cur.execute("""
            INSERT INTO accounts (account_id, email, email_verified, created_at)
            VALUES (%s, %s, true, %s)
            ON CONFLICT (email) DO UPDATE SET email_verified = true, agent_id = NULL
            RETURNING account_id
        """, (str(account_id), email, now))
        account_id = cur.fetchone()[0]
        print(f"  {GREEN}✓ Account: {str(account_id)[:8]}...{RESET}")

        # Create verified email verification with registration token
        verification_id = uuid.uuid4()
        verification_token = secrets.token_urlsafe(48)
        registration_token = secrets.token_urlsafe(48)

        cur.execute("""
            INSERT INTO email_verifications
                (verification_id, email, purpose, token, registration_token,
                 registration_token_expires_at, expires_at, used, created_at)
            VALUES (%s, %s, 'signup', %s, %s, %s, %s, true, %s)
        """, (
            str(verification_id), email, verification_token,
            registration_token, token_expires, now + timedelta(days=1), now,
        ))
        tokens[name.lower()] = registration_token
        print(f"  {GREEN}✓ Registration token: {registration_token[:16]}...{RESET}")

    conn.commit()
    cur.close()
    conn.close()

    # Write tokens to .env.demo
    env_file = os.path.join(os.path.dirname(__file__), ".env.demo")
    with open(env_file, "w") as f:
        f.write("# Auto-generated by demo_setup.py — valid for 1 hour\n")
        f.write(f"# Created: {now.isoformat()}\n")
        f.write(f"ALICE_REGISTRATION_TOKEN={tokens['alice']}\n")
        f.write(f"BOB_REGISTRATION_TOKEN={tokens['bob']}\n")

    print(f"\n{GREEN}{BOLD}✓ Setup complete!{RESET}")
    print(f"  Tokens written to {env_file}")
    print(f"  Valid until: {token_expires.isoformat()}")
    print(f"\n  {DIM}Run the demo:{RESET}")
    print(f"  ./run_staging.sh success")


if __name__ == "__main__":
    main()
