/**
 * k6 Load Test Suite — Agent Registry
 *
 * Tests:
 *  1. Discovery & read endpoints (GET /discover, GET /agents/:id)
 *  2. Job lifecycle under concurrency (propose → accept → fund → deliver → verify)
 *  3. Rate limiting validation (burst beyond limits, expect 429s)
 *  4. Concurrent escrow operations (stress row-level locking)
 *
 * Prerequisites:
 *  1. Run setup.py to create test agents and test-data.json
 *  2. Start signer.py proxy (handles Ed25519 signing for k6)
 *  3. Run: k6 run load-tests/main.js
 *
 * Architecture:
 *  k6 → signer proxy (:9999) → API (:8080 or staging)
 *  The signer proxy adds Ed25519 signatures to each request.
 */

import http from 'k6/http';
import { check, group, sleep } from 'k6';
import { Counter, Rate, Trend } from 'k6/metrics';
import { SharedArray } from 'k6/data';

// ─── Configuration ───

const SIGNER_URL = __ENV.SIGNER_URL || 'http://127.0.0.1:9999';

// Load test data generated by setup.py
const testData = JSON.parse(open('./test-data.json'));
const agents = new SharedArray('agents', () => testData.agents);
const listings = new SharedArray('listings', () => testData.listings);
const buyerIds = testData.buyers;
const sellerIds = testData.sellers;

// ─── Custom Metrics ───

const rateLimitHits = new Counter('rate_limit_hits');
const escrowOps = new Counter('escrow_operations');
const jobsCreated = new Counter('jobs_created');
const jobsCompleted = new Counter('jobs_completed');
const errorRate = new Rate('error_rate');
const discoveryDuration = new Trend('discovery_duration', true);
const jobLifecycleDuration = new Trend('job_lifecycle_duration', true);

// ─── Test Scenarios ───

export const options = {
  scenarios: {
    // Scenario 1: Sustained read load (discovery, agent lookups)
    read_load: {
      executor: 'constant-arrival-rate',
      exec: 'readEndpoints',
      rate: 50,           // 50 requests/sec
      timeUnit: '1s',
      duration: '2m',
      preAllocatedVUs: 20,
      maxVUs: 50,
      startTime: '0s',
    },

    // Scenario 2: Job lifecycle (write-heavy)
    job_lifecycle: {
      executor: 'ramping-vus',
      exec: 'jobLifecycle',
      startVUs: 2,
      stages: [
        { duration: '30s', target: 5 },    // Ramp up
        { duration: '1m', target: 10 },     // Sustained
        { duration: '30s', target: 20 },    // Peak
        { duration: '30s', target: 0 },     // Ramp down
      ],
      startTime: '10s',
    },

    // Scenario 3: Rate limit validation (burst)
    rate_limit_burst: {
      executor: 'per-vu-iterations',
      exec: 'rateLimitTest',
      vus: 5,
      iterations: 1,
      startTime: '2m30s',  // After main load
    },

    // Scenario 4: Concurrent escrow stress
    escrow_stress: {
      executor: 'constant-vus',
      exec: 'escrowStress',
      vus: 10,
      duration: '1m',
      startTime: '3m',
    },
  },

  thresholds: {
    http_req_duration: ['p(95)<500', 'p(99)<1000'],  // 95th < 500ms, 99th < 1s
    error_rate: ['rate<0.05'],                         // < 5% errors
    'http_req_duration{scenario:read_load}': ['p(95)<200'],  // Reads should be fast
  },
};

// ─── Helpers ───

function getAgent(agentId) {
  return agents.find(a => a.agent_id === agentId);
}

function randomBuyer() {
  const id = buyerIds[Math.floor(Math.random() * buyerIds.length)];
  return getAgent(id);
}

function randomSeller() {
  const id = sellerIds[Math.floor(Math.random() * sellerIds.length)];
  return getAgent(id);
}

function randomListing() {
  return listings[Math.floor(Math.random() * listings.length)];
}

function signedHeaders(agent) {
  return {
    'Content-Type': 'application/json',
    'X-Agent-Id': agent.agent_id,
    'X-Private-Key': agent.private_key,
  };
}

function apiGet(path, agent) {
  return http.get(`${SIGNER_URL}${path}`, { headers: signedHeaders(agent) });
}

function apiPost(path, body, agent) {
  return http.post(`${SIGNER_URL}${path}`, JSON.stringify(body), {
    headers: signedHeaders(agent),
  });
}

// ─── Scenario 1: Read Endpoints ───

export function readEndpoints() {
  const agent = agents[Math.floor(Math.random() * agents.length)];

  group('discovery', () => {
    const start = Date.now();
    const res = apiGet('/v1/discover?skill_id=load-test', agent);
    discoveryDuration.add(Date.now() - start);

    const ok = check(res, {
      'discover status 200': (r) => r.status === 200,
      'discover returns items': (r) => {
        const body = r.json();
        return body && Array.isArray(body.items);
      },
    });
    errorRate.add(!ok);
  });

  group('agent_lookup', () => {
    // Look up a random other agent
    const other = agents[Math.floor(Math.random() * agents.length)];
    const res = apiGet(`/v1/agents/${other.agent_id}`, agent);

    const ok = check(res, {
      'agent lookup status 200': (r) => r.status === 200,
      'agent has display_name': (r) => r.json().display_name !== undefined,
    });
    errorRate.add(!ok);
  });

  group('listings', () => {
    const res = apiGet('/v1/listings?limit=10', agent);

    const ok = check(res, {
      'listings status 200': (r) => r.status === 200,
    });
    errorRate.add(!ok);
  });

  sleep(0.1);  // Small pause between iterations
}

// ─── Scenario 2: Job Lifecycle ───

export function jobLifecycle() {
  const buyer = randomBuyer();
  const listing = randomListing();
  const seller = getAgent(listing.seller_id);

  if (!buyer || !seller) return;

  const start = Date.now();
  let jobId;

  group('propose_job', () => {
    const res = apiPost('/v1/jobs', {
      seller_agent_id: seller.agent_id,
      listing_id: listing.listing_id,
      max_budget: '5.00',
      acceptance_criteria: null,
      requirements: { task: 'load-test-task' },
      delivery_deadline: new Date(Date.now() + 3600000).toISOString(),
      max_rounds: 3,
    }, buyer);

    const ok = check(res, {
      'job created': (r) => r.status === 201,
    });

    if (res.status === 201) {
      jobId = res.json().job_id;
      jobsCreated.add(1);
    }
    errorRate.add(!ok);
  });

  if (!jobId) return;

  sleep(0.2);

  group('accept_job', () => {
    const res = apiPost(`/v1/jobs/${jobId}/accept`, {}, seller);
    check(res, { 'job accepted': (r) => r.status === 200 });
  });

  sleep(0.2);

  group('fund_job', () => {
    const res = apiPost(`/v1/jobs/${jobId}/fund`, {}, buyer);
    const ok = check(res, { 'job funded': (r) => r.status === 200 || r.status === 201 });
    if (ok) escrowOps.add(1);
  });

  sleep(0.2);

  group('start_job', () => {
    const res = apiPost(`/v1/jobs/${jobId}/start`, {}, seller);
    check(res, { 'job started': (r) => r.status === 200 });
  });

  sleep(0.2);

  group('deliver_job', () => {
    const res = apiPost(`/v1/jobs/${jobId}/deliver`, {
      result: { output: 'load-test-output', data: [1, 2, 3] },
    }, seller);
    check(res, { 'job delivered': (r) => r.status === 200 });
  });

  sleep(0.2);

  group('complete_job', () => {
    // Complete without verification (no acceptance_criteria set)
    const res = apiPost(`/v1/jobs/${jobId}/complete`, {}, buyer);
    const ok = check(res, { 'job completed': (r) => r.status === 200 });
    if (ok) {
      jobsCompleted.add(1);
      escrowOps.add(1);
    }
  });

  jobLifecycleDuration.add(Date.now() - start);
  sleep(1);  // Pause between full lifecycle runs
}

// ─── Scenario 3: Rate Limit Validation ───

export function rateLimitTest() {
  const agent = agents[__VU % agents.length];

  group('burst_discovery', () => {
    let hit429 = false;

    // Fire 100 rapid requests — should trigger rate limit (60 tokens for discovery)
    for (let i = 0; i < 100; i++) {
      const res = apiGet('/v1/discover?skill_id=load-test', agent);

      if (res.status === 429) {
        hit429 = true;
        rateLimitHits.add(1);

        check(res, {
          'rate limit returns 429': (r) => r.status === 429,
          'rate limit has retry-after header': (r) =>
            r.headers['Retry-After'] !== undefined ||
            r.headers['retry-after'] !== undefined,
        });
        break;
      }
    }

    check(null, {
      'rate limiter triggered': () => hit429,
    });
  });

  sleep(5);  // Let tokens refill

  group('burst_writes', () => {
    let hit429 = false;

    // Fire rapid write requests — should trigger write rate limit (30 tokens)
    for (let i = 0; i < 50; i++) {
      const listing = randomListing();
      const res = apiPost('/v1/jobs', {
        seller_agent_id: listing.seller_id,
        listing_id: listing.listing_id,
        max_budget: '1.00',
        requirements: { task: 'rate-limit-test' },
        delivery_deadline: new Date(Date.now() + 3600000).toISOString(),
      }, agent);

      if (res.status === 429) {
        hit429 = true;
        rateLimitHits.add(1);
        break;
      }
    }

    check(null, {
      'write rate limiter triggered': () => hit429,
    });
  });
}

// ─── Scenario 4: Concurrent Escrow Stress ───

export function escrowStress() {
  // Multiple VUs create and fund jobs simultaneously to stress row-level locking
  const buyer = randomBuyer();
  const listing = randomListing();
  const seller = getAgent(listing.seller_id);

  if (!buyer || !seller) return;

  // Create job
  const createRes = apiPost('/v1/jobs', {
    seller_agent_id: seller.agent_id,
    listing_id: listing.listing_id,
    max_budget: '2.00',
    requirements: { task: 'escrow-stress' },
    delivery_deadline: new Date(Date.now() + 3600000).toISOString(),
    max_rounds: 1,
  }, buyer);

  if (createRes.status !== 201) return;
  const jobId = createRes.json().job_id;
  jobsCreated.add(1);

  sleep(0.1);

  // Accept
  apiPost(`/v1/jobs/${jobId}/accept`, {}, seller);
  sleep(0.1);

  // Fund (this is the critical escrow operation)
  const fundRes = apiPost(`/v1/jobs/${jobId}/fund`, {}, buyer);
  const funded = check(fundRes, {
    'escrow funded under contention': (r) => r.status === 200 || r.status === 201,
  });

  if (funded) {
    escrowOps.add(1);

    sleep(0.1);

    // Start
    apiPost(`/v1/jobs/${jobId}/start`, {}, seller);
    sleep(0.1);

    // Deliver
    apiPost(`/v1/jobs/${jobId}/deliver`, {
      result: { output: 'stress-test' },
    }, seller);
    sleep(0.1);

    // Complete
    const completeRes = apiPost(`/v1/jobs/${jobId}/complete`, {}, buyer);
    if (completeRes.status === 200) {
      jobsCompleted.add(1);
      escrowOps.add(1);
    }
  }

  // Check balance consistency
  const balanceRes = apiGet(`/v1/agents/${buyer.agent_id}/balance`, buyer);
  check(balanceRes, {
    'balance endpoint healthy': (r) => r.status === 200,
    'balance is non-negative': (r) => parseFloat(r.json().balance) >= 0,
  });

  sleep(0.5);
}
